// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActiveSessionsColumns holds the columns for the "active_sessions" table.
	ActiveSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_id", Type: field.TypeString, Unique: true},
		{Name: "exchange", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString},
		{Name: "timeframe", Type: field.TypeEnum, Enums: []string{"10s", "1m", "5m", "1d"}},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ActiveSessionsTable holds the schema information for the "active_sessions" table.
	ActiveSessionsTable = &schema.Table{
		Name:       "active_sessions",
		Columns:    ActiveSessionsColumns,
		PrimaryKey: []*schema.Column{ActiveSessionsColumns[0]},
	}
	// CandlesColumns holds the columns for the "candles" table.
	CandlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "exchange", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString},
		{Name: "timeframe", Type: field.TypeEnum, Enums: []string{"10s", "1m", "5m", "1d"}},
		{Name: "timestamp", Type: field.TypeInt64},
		{Name: "open", Type: field.TypeFloat64},
		{Name: "high", Type: field.TypeFloat64},
		{Name: "low", Type: field.TypeFloat64},
		{Name: "close", Type: field.TypeFloat64},
		{Name: "volume", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CandlesTable holds the schema information for the "candles" table.
	CandlesTable = &schema.Table{
		Name:       "candles",
		Columns:    CandlesColumns,
		PrimaryKey: []*schema.Column{CandlesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "candle_exchange_symbol",
				Unique:  false,
				Columns: []*schema.Column{CandlesColumns[1], CandlesColumns[2]},
			},
			{
				Name:    "candle_timestamp",
				Unique:  false,
				Columns: []*schema.Column{CandlesColumns[4]},
			},
			{
				Name:    "candle_exchange_symbol_timeframe_timestamp",
				Unique:  true,
				Columns: []*schema.Column{CandlesColumns[1], CandlesColumns[2], CandlesColumns[3], CandlesColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActiveSessionsTable,
		CandlesTable,
	}
)

func init() {
}
