// Code generated by ent, DO NOT EDIT.

package candle

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/iiiyu/tradingview-ws-client/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Candle {
	return predicate.Candle(sql.FieldLTE(FieldID, id))
}

// Exchange applies equality check predicate on the "exchange" field. It's identical to ExchangeEQ.
func Exchange(v string) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldExchange, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldSymbol, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldTimestamp, v))
}

// Open applies equality check predicate on the "open" field. It's identical to OpenEQ.
func Open(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldOpen, vc))
}

// High applies equality check predicate on the "high" field. It's identical to HighEQ.
func High(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldHigh, vc))
}

// Low applies equality check predicate on the "low" field. It's identical to LowEQ.
func Low(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldLow, vc))
}

// Close applies equality check predicate on the "close" field. It's identical to CloseEQ.
func Close(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldClose, vc))
}

// Volume applies equality check predicate on the "volume" field. It's identical to VolumeEQ.
func Volume(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldVolume, vc))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldCreatedAt, v))
}

// ExchangeEQ applies the EQ predicate on the "exchange" field.
func ExchangeEQ(v string) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldExchange, v))
}

// ExchangeNEQ applies the NEQ predicate on the "exchange" field.
func ExchangeNEQ(v string) predicate.Candle {
	return predicate.Candle(sql.FieldNEQ(FieldExchange, v))
}

// ExchangeIn applies the In predicate on the "exchange" field.
func ExchangeIn(vs ...string) predicate.Candle {
	return predicate.Candle(sql.FieldIn(FieldExchange, vs...))
}

// ExchangeNotIn applies the NotIn predicate on the "exchange" field.
func ExchangeNotIn(vs ...string) predicate.Candle {
	return predicate.Candle(sql.FieldNotIn(FieldExchange, vs...))
}

// ExchangeGT applies the GT predicate on the "exchange" field.
func ExchangeGT(v string) predicate.Candle {
	return predicate.Candle(sql.FieldGT(FieldExchange, v))
}

// ExchangeGTE applies the GTE predicate on the "exchange" field.
func ExchangeGTE(v string) predicate.Candle {
	return predicate.Candle(sql.FieldGTE(FieldExchange, v))
}

// ExchangeLT applies the LT predicate on the "exchange" field.
func ExchangeLT(v string) predicate.Candle {
	return predicate.Candle(sql.FieldLT(FieldExchange, v))
}

// ExchangeLTE applies the LTE predicate on the "exchange" field.
func ExchangeLTE(v string) predicate.Candle {
	return predicate.Candle(sql.FieldLTE(FieldExchange, v))
}

// ExchangeContains applies the Contains predicate on the "exchange" field.
func ExchangeContains(v string) predicate.Candle {
	return predicate.Candle(sql.FieldContains(FieldExchange, v))
}

// ExchangeHasPrefix applies the HasPrefix predicate on the "exchange" field.
func ExchangeHasPrefix(v string) predicate.Candle {
	return predicate.Candle(sql.FieldHasPrefix(FieldExchange, v))
}

// ExchangeHasSuffix applies the HasSuffix predicate on the "exchange" field.
func ExchangeHasSuffix(v string) predicate.Candle {
	return predicate.Candle(sql.FieldHasSuffix(FieldExchange, v))
}

// ExchangeEqualFold applies the EqualFold predicate on the "exchange" field.
func ExchangeEqualFold(v string) predicate.Candle {
	return predicate.Candle(sql.FieldEqualFold(FieldExchange, v))
}

// ExchangeContainsFold applies the ContainsFold predicate on the "exchange" field.
func ExchangeContainsFold(v string) predicate.Candle {
	return predicate.Candle(sql.FieldContainsFold(FieldExchange, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Candle {
	return predicate.Candle(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Candle {
	return predicate.Candle(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Candle {
	return predicate.Candle(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Candle {
	return predicate.Candle(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Candle {
	return predicate.Candle(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Candle {
	return predicate.Candle(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Candle {
	return predicate.Candle(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Candle {
	return predicate.Candle(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Candle {
	return predicate.Candle(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Candle {
	return predicate.Candle(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Candle {
	return predicate.Candle(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Candle {
	return predicate.Candle(sql.FieldContainsFold(FieldSymbol, v))
}

// TimeframeEQ applies the EQ predicate on the "timeframe" field.
func TimeframeEQ(v Timeframe) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldTimeframe, v))
}

// TimeframeNEQ applies the NEQ predicate on the "timeframe" field.
func TimeframeNEQ(v Timeframe) predicate.Candle {
	return predicate.Candle(sql.FieldNEQ(FieldTimeframe, v))
}

// TimeframeIn applies the In predicate on the "timeframe" field.
func TimeframeIn(vs ...Timeframe) predicate.Candle {
	return predicate.Candle(sql.FieldIn(FieldTimeframe, vs...))
}

// TimeframeNotIn applies the NotIn predicate on the "timeframe" field.
func TimeframeNotIn(vs ...Timeframe) predicate.Candle {
	return predicate.Candle(sql.FieldNotIn(FieldTimeframe, vs...))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...int64) predicate.Candle {
	return predicate.Candle(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...int64) predicate.Candle {
	return predicate.Candle(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v int64) predicate.Candle {
	return predicate.Candle(sql.FieldLTE(FieldTimestamp, v))
}

// OpenEQ applies the EQ predicate on the "open" field.
func OpenEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldOpen, vc))
}

// OpenNEQ applies the NEQ predicate on the "open" field.
func OpenNEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldNEQ(FieldOpen, vc))
}

// OpenIn applies the In predicate on the "open" field.
func OpenIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldIn(FieldOpen, v...))
}

// OpenNotIn applies the NotIn predicate on the "open" field.
func OpenNotIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldNotIn(FieldOpen, v...))
}

// OpenGT applies the GT predicate on the "open" field.
func OpenGT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGT(FieldOpen, vc))
}

// OpenGTE applies the GTE predicate on the "open" field.
func OpenGTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGTE(FieldOpen, vc))
}

// OpenLT applies the LT predicate on the "open" field.
func OpenLT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLT(FieldOpen, vc))
}

// OpenLTE applies the LTE predicate on the "open" field.
func OpenLTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLTE(FieldOpen, vc))
}

// HighEQ applies the EQ predicate on the "high" field.
func HighEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldHigh, vc))
}

// HighNEQ applies the NEQ predicate on the "high" field.
func HighNEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldNEQ(FieldHigh, vc))
}

// HighIn applies the In predicate on the "high" field.
func HighIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldIn(FieldHigh, v...))
}

// HighNotIn applies the NotIn predicate on the "high" field.
func HighNotIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldNotIn(FieldHigh, v...))
}

// HighGT applies the GT predicate on the "high" field.
func HighGT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGT(FieldHigh, vc))
}

// HighGTE applies the GTE predicate on the "high" field.
func HighGTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGTE(FieldHigh, vc))
}

// HighLT applies the LT predicate on the "high" field.
func HighLT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLT(FieldHigh, vc))
}

// HighLTE applies the LTE predicate on the "high" field.
func HighLTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLTE(FieldHigh, vc))
}

// LowEQ applies the EQ predicate on the "low" field.
func LowEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldLow, vc))
}

// LowNEQ applies the NEQ predicate on the "low" field.
func LowNEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldNEQ(FieldLow, vc))
}

// LowIn applies the In predicate on the "low" field.
func LowIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldIn(FieldLow, v...))
}

// LowNotIn applies the NotIn predicate on the "low" field.
func LowNotIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldNotIn(FieldLow, v...))
}

// LowGT applies the GT predicate on the "low" field.
func LowGT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGT(FieldLow, vc))
}

// LowGTE applies the GTE predicate on the "low" field.
func LowGTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGTE(FieldLow, vc))
}

// LowLT applies the LT predicate on the "low" field.
func LowLT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLT(FieldLow, vc))
}

// LowLTE applies the LTE predicate on the "low" field.
func LowLTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLTE(FieldLow, vc))
}

// CloseEQ applies the EQ predicate on the "close" field.
func CloseEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldClose, vc))
}

// CloseNEQ applies the NEQ predicate on the "close" field.
func CloseNEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldNEQ(FieldClose, vc))
}

// CloseIn applies the In predicate on the "close" field.
func CloseIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldIn(FieldClose, v...))
}

// CloseNotIn applies the NotIn predicate on the "close" field.
func CloseNotIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldNotIn(FieldClose, v...))
}

// CloseGT applies the GT predicate on the "close" field.
func CloseGT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGT(FieldClose, vc))
}

// CloseGTE applies the GTE predicate on the "close" field.
func CloseGTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGTE(FieldClose, vc))
}

// CloseLT applies the LT predicate on the "close" field.
func CloseLT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLT(FieldClose, vc))
}

// CloseLTE applies the LTE predicate on the "close" field.
func CloseLTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLTE(FieldClose, vc))
}

// VolumeEQ applies the EQ predicate on the "volume" field.
func VolumeEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldEQ(FieldVolume, vc))
}

// VolumeNEQ applies the NEQ predicate on the "volume" field.
func VolumeNEQ(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldNEQ(FieldVolume, vc))
}

// VolumeIn applies the In predicate on the "volume" field.
func VolumeIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldIn(FieldVolume, v...))
}

// VolumeNotIn applies the NotIn predicate on the "volume" field.
func VolumeNotIn(vs ...float64) predicate.Candle {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = float64(vs[i])
	}
	return predicate.Candle(sql.FieldNotIn(FieldVolume, v...))
}

// VolumeGT applies the GT predicate on the "volume" field.
func VolumeGT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGT(FieldVolume, vc))
}

// VolumeGTE applies the GTE predicate on the "volume" field.
func VolumeGTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldGTE(FieldVolume, vc))
}

// VolumeLT applies the LT predicate on the "volume" field.
func VolumeLT(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLT(FieldVolume, vc))
}

// VolumeLTE applies the LTE predicate on the "volume" field.
func VolumeLTE(v float64) predicate.Candle {
	vc := float64(v)
	return predicate.Candle(sql.FieldLTE(FieldVolume, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Candle {
	return predicate.Candle(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Candle) predicate.Candle {
	return predicate.Candle(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Candle) predicate.Candle {
	return predicate.Candle(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Candle) predicate.Candle {
	return predicate.Candle(sql.NotPredicates(p))
}
