// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/iiiyu/tradingview-ws-client/ent/activesession"
)

// ActiveSessionCreate is the builder for creating a ActiveSession entity.
type ActiveSessionCreate struct {
	config
	mutation *ActiveSessionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (asc *ActiveSessionCreate) SetSessionID(s string) *ActiveSessionCreate {
	asc.mutation.SetSessionID(s)
	return asc
}

// SetExchange sets the "exchange" field.
func (asc *ActiveSessionCreate) SetExchange(s string) *ActiveSessionCreate {
	asc.mutation.SetExchange(s)
	return asc
}

// SetSymbol sets the "symbol" field.
func (asc *ActiveSessionCreate) SetSymbol(s string) *ActiveSessionCreate {
	asc.mutation.SetSymbol(s)
	return asc
}

// SetType sets the "type" field.
func (asc *ActiveSessionCreate) SetType(a activesession.Type) *ActiveSessionCreate {
	asc.mutation.SetType(a)
	return asc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (asc *ActiveSessionCreate) SetNillableType(a *activesession.Type) *ActiveSessionCreate {
	if a != nil {
		asc.SetType(*a)
	}
	return asc
}

// SetTimeframe sets the "timeframe" field.
func (asc *ActiveSessionCreate) SetTimeframe(a activesession.Timeframe) *ActiveSessionCreate {
	asc.mutation.SetTimeframe(a)
	return asc
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (asc *ActiveSessionCreate) SetNillableTimeframe(a *activesession.Timeframe) *ActiveSessionCreate {
	if a != nil {
		asc.SetTimeframe(*a)
	}
	return asc
}

// SetEnabled sets the "enabled" field.
func (asc *ActiveSessionCreate) SetEnabled(b bool) *ActiveSessionCreate {
	asc.mutation.SetEnabled(b)
	return asc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (asc *ActiveSessionCreate) SetNillableEnabled(b *bool) *ActiveSessionCreate {
	if b != nil {
		asc.SetEnabled(*b)
	}
	return asc
}

// SetCreatedAt sets the "created_at" field.
func (asc *ActiveSessionCreate) SetCreatedAt(t time.Time) *ActiveSessionCreate {
	asc.mutation.SetCreatedAt(t)
	return asc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (asc *ActiveSessionCreate) SetNillableCreatedAt(t *time.Time) *ActiveSessionCreate {
	if t != nil {
		asc.SetCreatedAt(*t)
	}
	return asc
}

// SetUpdatedAt sets the "updated_at" field.
func (asc *ActiveSessionCreate) SetUpdatedAt(t time.Time) *ActiveSessionCreate {
	asc.mutation.SetUpdatedAt(t)
	return asc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (asc *ActiveSessionCreate) SetNillableUpdatedAt(t *time.Time) *ActiveSessionCreate {
	if t != nil {
		asc.SetUpdatedAt(*t)
	}
	return asc
}

// SetID sets the "id" field.
func (asc *ActiveSessionCreate) SetID(u uuid.UUID) *ActiveSessionCreate {
	asc.mutation.SetID(u)
	return asc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (asc *ActiveSessionCreate) SetNillableID(u *uuid.UUID) *ActiveSessionCreate {
	if u != nil {
		asc.SetID(*u)
	}
	return asc
}

// Mutation returns the ActiveSessionMutation object of the builder.
func (asc *ActiveSessionCreate) Mutation() *ActiveSessionMutation {
	return asc.mutation
}

// Save creates the ActiveSession in the database.
func (asc *ActiveSessionCreate) Save(ctx context.Context) (*ActiveSession, error) {
	asc.defaults()
	return withHooks(ctx, asc.sqlSave, asc.mutation, asc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (asc *ActiveSessionCreate) SaveX(ctx context.Context) *ActiveSession {
	v, err := asc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (asc *ActiveSessionCreate) Exec(ctx context.Context) error {
	_, err := asc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asc *ActiveSessionCreate) ExecX(ctx context.Context) {
	if err := asc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asc *ActiveSessionCreate) defaults() {
	if _, ok := asc.mutation.GetType(); !ok {
		v := activesession.DefaultType
		asc.mutation.SetType(v)
	}
	if _, ok := asc.mutation.Enabled(); !ok {
		v := activesession.DefaultEnabled
		asc.mutation.SetEnabled(v)
	}
	if _, ok := asc.mutation.CreatedAt(); !ok {
		v := activesession.DefaultCreatedAt()
		asc.mutation.SetCreatedAt(v)
	}
	if _, ok := asc.mutation.UpdatedAt(); !ok {
		v := activesession.DefaultUpdatedAt()
		asc.mutation.SetUpdatedAt(v)
	}
	if _, ok := asc.mutation.ID(); !ok {
		v := activesession.DefaultID()
		asc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asc *ActiveSessionCreate) check() error {
	if _, ok := asc.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ActiveSession.session_id"`)}
	}
	if _, ok := asc.mutation.Exchange(); !ok {
		return &ValidationError{Name: "exchange", err: errors.New(`ent: missing required field "ActiveSession.exchange"`)}
	}
	if _, ok := asc.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "ActiveSession.symbol"`)}
	}
	if _, ok := asc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ActiveSession.type"`)}
	}
	if v, ok := asc.mutation.GetType(); ok {
		if err := activesession.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ActiveSession.type": %w`, err)}
		}
	}
	if v, ok := asc.mutation.Timeframe(); ok {
		if err := activesession.TimeframeValidator(v); err != nil {
			return &ValidationError{Name: "timeframe", err: fmt.Errorf(`ent: validator failed for field "ActiveSession.timeframe": %w`, err)}
		}
	}
	if _, ok := asc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ActiveSession.enabled"`)}
	}
	if _, ok := asc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActiveSession.created_at"`)}
	}
	if _, ok := asc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActiveSession.updated_at"`)}
	}
	return nil
}

func (asc *ActiveSessionCreate) sqlSave(ctx context.Context) (*ActiveSession, error) {
	if err := asc.check(); err != nil {
		return nil, err
	}
	_node, _spec := asc.createSpec()
	if err := sqlgraph.CreateNode(ctx, asc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	asc.mutation.id = &_node.ID
	asc.mutation.done = true
	return _node, nil
}

func (asc *ActiveSessionCreate) createSpec() (*ActiveSession, *sqlgraph.CreateSpec) {
	var (
		_node = &ActiveSession{config: asc.config}
		_spec = sqlgraph.NewCreateSpec(activesession.Table, sqlgraph.NewFieldSpec(activesession.FieldID, field.TypeUUID))
	)
	if id, ok := asc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := asc.mutation.SessionID(); ok {
		_spec.SetField(activesession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := asc.mutation.Exchange(); ok {
		_spec.SetField(activesession.FieldExchange, field.TypeString, value)
		_node.Exchange = value
	}
	if value, ok := asc.mutation.Symbol(); ok {
		_spec.SetField(activesession.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := asc.mutation.GetType(); ok {
		_spec.SetField(activesession.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := asc.mutation.Timeframe(); ok {
		_spec.SetField(activesession.FieldTimeframe, field.TypeEnum, value)
		_node.Timeframe = &value
	}
	if value, ok := asc.mutation.Enabled(); ok {
		_spec.SetField(activesession.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := asc.mutation.CreatedAt(); ok {
		_spec.SetField(activesession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := asc.mutation.UpdatedAt(); ok {
		_spec.SetField(activesession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ActiveSessionCreateBulk is the builder for creating many ActiveSession entities in bulk.
type ActiveSessionCreateBulk struct {
	config
	err      error
	builders []*ActiveSessionCreate
}

// Save creates the ActiveSession entities in the database.
func (ascb *ActiveSessionCreateBulk) Save(ctx context.Context) ([]*ActiveSession, error) {
	if ascb.err != nil {
		return nil, ascb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ascb.builders))
	nodes := make([]*ActiveSession, len(ascb.builders))
	mutators := make([]Mutator, len(ascb.builders))
	for i := range ascb.builders {
		func(i int, root context.Context) {
			builder := ascb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActiveSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ascb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ascb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ascb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ascb *ActiveSessionCreateBulk) SaveX(ctx context.Context) []*ActiveSession {
	v, err := ascb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ascb *ActiveSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := ascb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ascb *ActiveSessionCreateBulk) ExecX(ctx context.Context) {
	if err := ascb.Exec(ctx); err != nil {
		panic(err)
	}
}
