// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iiiyu/tradingview-ws-client/ent/activesession"
	"github.com/iiiyu/tradingview-ws-client/ent/predicate"
)

// ActiveSessionQuery is the builder for querying ActiveSession entities.
type ActiveSessionQuery struct {
	config
	ctx        *QueryContext
	order      []activesession.OrderOption
	inters     []Interceptor
	predicates []predicate.ActiveSession
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ActiveSessionQuery builder.
func (asq *ActiveSessionQuery) Where(ps ...predicate.ActiveSession) *ActiveSessionQuery {
	asq.predicates = append(asq.predicates, ps...)
	return asq
}

// Limit the number of records to be returned by this query.
func (asq *ActiveSessionQuery) Limit(limit int) *ActiveSessionQuery {
	asq.ctx.Limit = &limit
	return asq
}

// Offset to start from.
func (asq *ActiveSessionQuery) Offset(offset int) *ActiveSessionQuery {
	asq.ctx.Offset = &offset
	return asq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (asq *ActiveSessionQuery) Unique(unique bool) *ActiveSessionQuery {
	asq.ctx.Unique = &unique
	return asq
}

// Order specifies how the records should be ordered.
func (asq *ActiveSessionQuery) Order(o ...activesession.OrderOption) *ActiveSessionQuery {
	asq.order = append(asq.order, o...)
	return asq
}

// First returns the first ActiveSession entity from the query.
// Returns a *NotFoundError when no ActiveSession was found.
func (asq *ActiveSessionQuery) First(ctx context.Context) (*ActiveSession, error) {
	nodes, err := asq.Limit(1).All(setContextOp(ctx, asq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{activesession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (asq *ActiveSessionQuery) FirstX(ctx context.Context) *ActiveSession {
	node, err := asq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ActiveSession ID from the query.
// Returns a *NotFoundError when no ActiveSession ID was found.
func (asq *ActiveSessionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(1).IDs(setContextOp(ctx, asq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{activesession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (asq *ActiveSessionQuery) FirstIDX(ctx context.Context) int {
	id, err := asq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ActiveSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ActiveSession entity is found.
// Returns a *NotFoundError when no ActiveSession entities are found.
func (asq *ActiveSessionQuery) Only(ctx context.Context) (*ActiveSession, error) {
	nodes, err := asq.Limit(2).All(setContextOp(ctx, asq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{activesession.Label}
	default:
		return nil, &NotSingularError{activesession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (asq *ActiveSessionQuery) OnlyX(ctx context.Context) *ActiveSession {
	node, err := asq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ActiveSession ID in the query.
// Returns a *NotSingularError when more than one ActiveSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (asq *ActiveSessionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(2).IDs(setContextOp(ctx, asq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{activesession.Label}
	default:
		err = &NotSingularError{activesession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (asq *ActiveSessionQuery) OnlyIDX(ctx context.Context) int {
	id, err := asq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ActiveSessions.
func (asq *ActiveSessionQuery) All(ctx context.Context) ([]*ActiveSession, error) {
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryAll)
	if err := asq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ActiveSession, *ActiveSessionQuery]()
	return withInterceptors[[]*ActiveSession](ctx, asq, qr, asq.inters)
}

// AllX is like All, but panics if an error occurs.
func (asq *ActiveSessionQuery) AllX(ctx context.Context) []*ActiveSession {
	nodes, err := asq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ActiveSession IDs.
func (asq *ActiveSessionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if asq.ctx.Unique == nil && asq.path != nil {
		asq.Unique(true)
	}
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryIDs)
	if err = asq.Select(activesession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (asq *ActiveSessionQuery) IDsX(ctx context.Context) []int {
	ids, err := asq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (asq *ActiveSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryCount)
	if err := asq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, asq, querierCount[*ActiveSessionQuery](), asq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (asq *ActiveSessionQuery) CountX(ctx context.Context) int {
	count, err := asq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (asq *ActiveSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryExist)
	switch _, err := asq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (asq *ActiveSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := asq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ActiveSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (asq *ActiveSessionQuery) Clone() *ActiveSessionQuery {
	if asq == nil {
		return nil
	}
	return &ActiveSessionQuery{
		config:     asq.config,
		ctx:        asq.ctx.Clone(),
		order:      append([]activesession.OrderOption{}, asq.order...),
		inters:     append([]Interceptor{}, asq.inters...),
		predicates: append([]predicate.ActiveSession{}, asq.predicates...),
		// clone intermediate query.
		sql:  asq.sql.Clone(),
		path: asq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ActiveSession.Query().
//		GroupBy(activesession.FieldSessionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (asq *ActiveSessionQuery) GroupBy(field string, fields ...string) *ActiveSessionGroupBy {
	asq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ActiveSessionGroupBy{build: asq}
	grbuild.flds = &asq.ctx.Fields
	grbuild.label = activesession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//	}
//
//	client.ActiveSession.Query().
//		Select(activesession.FieldSessionID).
//		Scan(ctx, &v)
func (asq *ActiveSessionQuery) Select(fields ...string) *ActiveSessionSelect {
	asq.ctx.Fields = append(asq.ctx.Fields, fields...)
	sbuild := &ActiveSessionSelect{ActiveSessionQuery: asq}
	sbuild.label = activesession.Label
	sbuild.flds, sbuild.scan = &asq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ActiveSessionSelect configured with the given aggregations.
func (asq *ActiveSessionQuery) Aggregate(fns ...AggregateFunc) *ActiveSessionSelect {
	return asq.Select().Aggregate(fns...)
}

func (asq *ActiveSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range asq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, asq); err != nil {
				return err
			}
		}
	}
	for _, f := range asq.ctx.Fields {
		if !activesession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if asq.path != nil {
		prev, err := asq.path(ctx)
		if err != nil {
			return err
		}
		asq.sql = prev
	}
	return nil
}

func (asq *ActiveSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ActiveSession, error) {
	var (
		nodes = []*ActiveSession{}
		_spec = asq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ActiveSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ActiveSession{config: asq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, asq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (asq *ActiveSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := asq.querySpec()
	_spec.Node.Columns = asq.ctx.Fields
	if len(asq.ctx.Fields) > 0 {
		_spec.Unique = asq.ctx.Unique != nil && *asq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, asq.driver, _spec)
}

func (asq *ActiveSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(activesession.Table, activesession.Columns, sqlgraph.NewFieldSpec(activesession.FieldID, field.TypeInt))
	_spec.From = asq.sql
	if unique := asq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if asq.path != nil {
		_spec.Unique = true
	}
	if fields := asq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activesession.FieldID)
		for i := range fields {
			if fields[i] != activesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := asq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := asq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := asq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := asq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (asq *ActiveSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(asq.driver.Dialect())
	t1 := builder.Table(activesession.Table)
	columns := asq.ctx.Fields
	if len(columns) == 0 {
		columns = activesession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if asq.sql != nil {
		selector = asq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if asq.ctx.Unique != nil && *asq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range asq.predicates {
		p(selector)
	}
	for _, p := range asq.order {
		p(selector)
	}
	if offset := asq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := asq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ActiveSessionGroupBy is the group-by builder for ActiveSession entities.
type ActiveSessionGroupBy struct {
	selector
	build *ActiveSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (asgb *ActiveSessionGroupBy) Aggregate(fns ...AggregateFunc) *ActiveSessionGroupBy {
	asgb.fns = append(asgb.fns, fns...)
	return asgb
}

// Scan applies the selector query and scans the result into the given value.
func (asgb *ActiveSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, asgb.build.ctx, ent.OpQueryGroupBy)
	if err := asgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActiveSessionQuery, *ActiveSessionGroupBy](ctx, asgb.build, asgb, asgb.build.inters, v)
}

func (asgb *ActiveSessionGroupBy) sqlScan(ctx context.Context, root *ActiveSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(asgb.fns))
	for _, fn := range asgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*asgb.flds)+len(asgb.fns))
		for _, f := range *asgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*asgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := asgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ActiveSessionSelect is the builder for selecting fields of ActiveSession entities.
type ActiveSessionSelect struct {
	*ActiveSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ass *ActiveSessionSelect) Aggregate(fns ...AggregateFunc) *ActiveSessionSelect {
	ass.fns = append(ass.fns, fns...)
	return ass
}

// Scan applies the selector query and scans the result into the given value.
func (ass *ActiveSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ass.ctx, ent.OpQuerySelect)
	if err := ass.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActiveSessionQuery, *ActiveSessionSelect](ctx, ass.ActiveSessionQuery, ass, ass.inters, v)
}

func (ass *ActiveSessionSelect) sqlScan(ctx context.Context, root *ActiveSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ass.fns))
	for _, fn := range ass.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ass.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
