// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iiiyu/tradingview-ws-client/ent/activesession"
	"github.com/iiiyu/tradingview-ws-client/ent/predicate"
)

// ActiveSessionUpdate is the builder for updating ActiveSession entities.
type ActiveSessionUpdate struct {
	config
	hooks    []Hook
	mutation *ActiveSessionMutation
}

// Where appends a list predicates to the ActiveSessionUpdate builder.
func (asu *ActiveSessionUpdate) Where(ps ...predicate.ActiveSession) *ActiveSessionUpdate {
	asu.mutation.Where(ps...)
	return asu
}

// SetSessionID sets the "session_id" field.
func (asu *ActiveSessionUpdate) SetSessionID(s string) *ActiveSessionUpdate {
	asu.mutation.SetSessionID(s)
	return asu
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableSessionID(s *string) *ActiveSessionUpdate {
	if s != nil {
		asu.SetSessionID(*s)
	}
	return asu
}

// SetExchange sets the "exchange" field.
func (asu *ActiveSessionUpdate) SetExchange(s string) *ActiveSessionUpdate {
	asu.mutation.SetExchange(s)
	return asu
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableExchange(s *string) *ActiveSessionUpdate {
	if s != nil {
		asu.SetExchange(*s)
	}
	return asu
}

// SetSymbol sets the "symbol" field.
func (asu *ActiveSessionUpdate) SetSymbol(s string) *ActiveSessionUpdate {
	asu.mutation.SetSymbol(s)
	return asu
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableSymbol(s *string) *ActiveSessionUpdate {
	if s != nil {
		asu.SetSymbol(*s)
	}
	return asu
}

// SetType sets the "type" field.
func (asu *ActiveSessionUpdate) SetType(a activesession.Type) *ActiveSessionUpdate {
	asu.mutation.SetType(a)
	return asu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableType(a *activesession.Type) *ActiveSessionUpdate {
	if a != nil {
		asu.SetType(*a)
	}
	return asu
}

// SetTimeframe sets the "timeframe" field.
func (asu *ActiveSessionUpdate) SetTimeframe(a activesession.Timeframe) *ActiveSessionUpdate {
	asu.mutation.SetTimeframe(a)
	return asu
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableTimeframe(a *activesession.Timeframe) *ActiveSessionUpdate {
	if a != nil {
		asu.SetTimeframe(*a)
	}
	return asu
}

// ClearTimeframe clears the value of the "timeframe" field.
func (asu *ActiveSessionUpdate) ClearTimeframe() *ActiveSessionUpdate {
	asu.mutation.ClearTimeframe()
	return asu
}

// SetEnabled sets the "enabled" field.
func (asu *ActiveSessionUpdate) SetEnabled(b bool) *ActiveSessionUpdate {
	asu.mutation.SetEnabled(b)
	return asu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableEnabled(b *bool) *ActiveSessionUpdate {
	if b != nil {
		asu.SetEnabled(*b)
	}
	return asu
}

// SetCreatedAt sets the "created_at" field.
func (asu *ActiveSessionUpdate) SetCreatedAt(t time.Time) *ActiveSessionUpdate {
	asu.mutation.SetCreatedAt(t)
	return asu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (asu *ActiveSessionUpdate) SetNillableCreatedAt(t *time.Time) *ActiveSessionUpdate {
	if t != nil {
		asu.SetCreatedAt(*t)
	}
	return asu
}

// SetUpdatedAt sets the "updated_at" field.
func (asu *ActiveSessionUpdate) SetUpdatedAt(t time.Time) *ActiveSessionUpdate {
	asu.mutation.SetUpdatedAt(t)
	return asu
}

// Mutation returns the ActiveSessionMutation object of the builder.
func (asu *ActiveSessionUpdate) Mutation() *ActiveSessionMutation {
	return asu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (asu *ActiveSessionUpdate) Save(ctx context.Context) (int, error) {
	asu.defaults()
	return withHooks(ctx, asu.sqlSave, asu.mutation, asu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asu *ActiveSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := asu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (asu *ActiveSessionUpdate) Exec(ctx context.Context) error {
	_, err := asu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asu *ActiveSessionUpdate) ExecX(ctx context.Context) {
	if err := asu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asu *ActiveSessionUpdate) defaults() {
	if _, ok := asu.mutation.UpdatedAt(); !ok {
		v := activesession.UpdateDefaultUpdatedAt()
		asu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asu *ActiveSessionUpdate) check() error {
	if v, ok := asu.mutation.GetType(); ok {
		if err := activesession.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ActiveSession.type": %w`, err)}
		}
	}
	if v, ok := asu.mutation.Timeframe(); ok {
		if err := activesession.TimeframeValidator(v); err != nil {
			return &ValidationError{Name: "timeframe", err: fmt.Errorf(`ent: validator failed for field "ActiveSession.timeframe": %w`, err)}
		}
	}
	return nil
}

func (asu *ActiveSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := asu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(activesession.Table, activesession.Columns, sqlgraph.NewFieldSpec(activesession.FieldID, field.TypeUUID))
	if ps := asu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asu.mutation.SessionID(); ok {
		_spec.SetField(activesession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := asu.mutation.Exchange(); ok {
		_spec.SetField(activesession.FieldExchange, field.TypeString, value)
	}
	if value, ok := asu.mutation.Symbol(); ok {
		_spec.SetField(activesession.FieldSymbol, field.TypeString, value)
	}
	if value, ok := asu.mutation.GetType(); ok {
		_spec.SetField(activesession.FieldType, field.TypeEnum, value)
	}
	if value, ok := asu.mutation.Timeframe(); ok {
		_spec.SetField(activesession.FieldTimeframe, field.TypeEnum, value)
	}
	if asu.mutation.TimeframeCleared() {
		_spec.ClearField(activesession.FieldTimeframe, field.TypeEnum)
	}
	if value, ok := asu.mutation.Enabled(); ok {
		_spec.SetField(activesession.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := asu.mutation.CreatedAt(); ok {
		_spec.SetField(activesession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := asu.mutation.UpdatedAt(); ok {
		_spec.SetField(activesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, asu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	asu.mutation.done = true
	return n, nil
}

// ActiveSessionUpdateOne is the builder for updating a single ActiveSession entity.
type ActiveSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActiveSessionMutation
}

// SetSessionID sets the "session_id" field.
func (asuo *ActiveSessionUpdateOne) SetSessionID(s string) *ActiveSessionUpdateOne {
	asuo.mutation.SetSessionID(s)
	return asuo
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableSessionID(s *string) *ActiveSessionUpdateOne {
	if s != nil {
		asuo.SetSessionID(*s)
	}
	return asuo
}

// SetExchange sets the "exchange" field.
func (asuo *ActiveSessionUpdateOne) SetExchange(s string) *ActiveSessionUpdateOne {
	asuo.mutation.SetExchange(s)
	return asuo
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableExchange(s *string) *ActiveSessionUpdateOne {
	if s != nil {
		asuo.SetExchange(*s)
	}
	return asuo
}

// SetSymbol sets the "symbol" field.
func (asuo *ActiveSessionUpdateOne) SetSymbol(s string) *ActiveSessionUpdateOne {
	asuo.mutation.SetSymbol(s)
	return asuo
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableSymbol(s *string) *ActiveSessionUpdateOne {
	if s != nil {
		asuo.SetSymbol(*s)
	}
	return asuo
}

// SetType sets the "type" field.
func (asuo *ActiveSessionUpdateOne) SetType(a activesession.Type) *ActiveSessionUpdateOne {
	asuo.mutation.SetType(a)
	return asuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableType(a *activesession.Type) *ActiveSessionUpdateOne {
	if a != nil {
		asuo.SetType(*a)
	}
	return asuo
}

// SetTimeframe sets the "timeframe" field.
func (asuo *ActiveSessionUpdateOne) SetTimeframe(a activesession.Timeframe) *ActiveSessionUpdateOne {
	asuo.mutation.SetTimeframe(a)
	return asuo
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableTimeframe(a *activesession.Timeframe) *ActiveSessionUpdateOne {
	if a != nil {
		asuo.SetTimeframe(*a)
	}
	return asuo
}

// ClearTimeframe clears the value of the "timeframe" field.
func (asuo *ActiveSessionUpdateOne) ClearTimeframe() *ActiveSessionUpdateOne {
	asuo.mutation.ClearTimeframe()
	return asuo
}

// SetEnabled sets the "enabled" field.
func (asuo *ActiveSessionUpdateOne) SetEnabled(b bool) *ActiveSessionUpdateOne {
	asuo.mutation.SetEnabled(b)
	return asuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableEnabled(b *bool) *ActiveSessionUpdateOne {
	if b != nil {
		asuo.SetEnabled(*b)
	}
	return asuo
}

// SetCreatedAt sets the "created_at" field.
func (asuo *ActiveSessionUpdateOne) SetCreatedAt(t time.Time) *ActiveSessionUpdateOne {
	asuo.mutation.SetCreatedAt(t)
	return asuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (asuo *ActiveSessionUpdateOne) SetNillableCreatedAt(t *time.Time) *ActiveSessionUpdateOne {
	if t != nil {
		asuo.SetCreatedAt(*t)
	}
	return asuo
}

// SetUpdatedAt sets the "updated_at" field.
func (asuo *ActiveSessionUpdateOne) SetUpdatedAt(t time.Time) *ActiveSessionUpdateOne {
	asuo.mutation.SetUpdatedAt(t)
	return asuo
}

// Mutation returns the ActiveSessionMutation object of the builder.
func (asuo *ActiveSessionUpdateOne) Mutation() *ActiveSessionMutation {
	return asuo.mutation
}

// Where appends a list predicates to the ActiveSessionUpdate builder.
func (asuo *ActiveSessionUpdateOne) Where(ps ...predicate.ActiveSession) *ActiveSessionUpdateOne {
	asuo.mutation.Where(ps...)
	return asuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (asuo *ActiveSessionUpdateOne) Select(field string, fields ...string) *ActiveSessionUpdateOne {
	asuo.fields = append([]string{field}, fields...)
	return asuo
}

// Save executes the query and returns the updated ActiveSession entity.
func (asuo *ActiveSessionUpdateOne) Save(ctx context.Context) (*ActiveSession, error) {
	asuo.defaults()
	return withHooks(ctx, asuo.sqlSave, asuo.mutation, asuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asuo *ActiveSessionUpdateOne) SaveX(ctx context.Context) *ActiveSession {
	node, err := asuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (asuo *ActiveSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := asuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asuo *ActiveSessionUpdateOne) ExecX(ctx context.Context) {
	if err := asuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asuo *ActiveSessionUpdateOne) defaults() {
	if _, ok := asuo.mutation.UpdatedAt(); !ok {
		v := activesession.UpdateDefaultUpdatedAt()
		asuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asuo *ActiveSessionUpdateOne) check() error {
	if v, ok := asuo.mutation.GetType(); ok {
		if err := activesession.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ActiveSession.type": %w`, err)}
		}
	}
	if v, ok := asuo.mutation.Timeframe(); ok {
		if err := activesession.TimeframeValidator(v); err != nil {
			return &ValidationError{Name: "timeframe", err: fmt.Errorf(`ent: validator failed for field "ActiveSession.timeframe": %w`, err)}
		}
	}
	return nil
}

func (asuo *ActiveSessionUpdateOne) sqlSave(ctx context.Context) (_node *ActiveSession, err error) {
	if err := asuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activesession.Table, activesession.Columns, sqlgraph.NewFieldSpec(activesession.FieldID, field.TypeUUID))
	id, ok := asuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActiveSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := asuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activesession.FieldID)
		for _, f := range fields {
			if !activesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := asuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asuo.mutation.SessionID(); ok {
		_spec.SetField(activesession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := asuo.mutation.Exchange(); ok {
		_spec.SetField(activesession.FieldExchange, field.TypeString, value)
	}
	if value, ok := asuo.mutation.Symbol(); ok {
		_spec.SetField(activesession.FieldSymbol, field.TypeString, value)
	}
	if value, ok := asuo.mutation.GetType(); ok {
		_spec.SetField(activesession.FieldType, field.TypeEnum, value)
	}
	if value, ok := asuo.mutation.Timeframe(); ok {
		_spec.SetField(activesession.FieldTimeframe, field.TypeEnum, value)
	}
	if asuo.mutation.TimeframeCleared() {
		_spec.ClearField(activesession.FieldTimeframe, field.TypeEnum)
	}
	if value, ok := asuo.mutation.Enabled(); ok {
		_spec.SetField(activesession.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := asuo.mutation.CreatedAt(); ok {
		_spec.SetField(activesession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := asuo.mutation.UpdatedAt(); ok {
		_spec.SetField(activesession.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ActiveSession{config: asuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, asuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	asuo.mutation.done = true
	return _node, nil
}
