// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iiiyu/tradingview-ws-client/ent/candle"
	"github.com/iiiyu/tradingview-ws-client/ent/predicate"
)

// CandleUpdate is the builder for updating Candle entities.
type CandleUpdate struct {
	config
	hooks    []Hook
	mutation *CandleMutation
}

// Where appends a list predicates to the CandleUpdate builder.
func (cu *CandleUpdate) Where(ps ...predicate.Candle) *CandleUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetExchange sets the "exchange" field.
func (cu *CandleUpdate) SetExchange(s string) *CandleUpdate {
	cu.mutation.SetExchange(s)
	return cu
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableExchange(s *string) *CandleUpdate {
	if s != nil {
		cu.SetExchange(*s)
	}
	return cu
}

// SetSymbol sets the "symbol" field.
func (cu *CandleUpdate) SetSymbol(s string) *CandleUpdate {
	cu.mutation.SetSymbol(s)
	return cu
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableSymbol(s *string) *CandleUpdate {
	if s != nil {
		cu.SetSymbol(*s)
	}
	return cu
}

// SetTimeframe sets the "timeframe" field.
func (cu *CandleUpdate) SetTimeframe(c candle.Timeframe) *CandleUpdate {
	cu.mutation.SetTimeframe(c)
	return cu
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableTimeframe(c *candle.Timeframe) *CandleUpdate {
	if c != nil {
		cu.SetTimeframe(*c)
	}
	return cu
}

// SetTimestamp sets the "timestamp" field.
func (cu *CandleUpdate) SetTimestamp(i int64) *CandleUpdate {
	cu.mutation.ResetTimestamp()
	cu.mutation.SetTimestamp(i)
	return cu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableTimestamp(i *int64) *CandleUpdate {
	if i != nil {
		cu.SetTimestamp(*i)
	}
	return cu
}

// AddTimestamp adds i to the "timestamp" field.
func (cu *CandleUpdate) AddTimestamp(i int64) *CandleUpdate {
	cu.mutation.AddTimestamp(i)
	return cu
}

// SetOpen sets the "open" field.
func (cu *CandleUpdate) SetOpen(f float64) *CandleUpdate {
	cu.mutation.ResetOpen()
	cu.mutation.SetOpen(f)
	return cu
}

// SetNillableOpen sets the "open" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableOpen(f *float64) *CandleUpdate {
	if f != nil {
		cu.SetOpen(*f)
	}
	return cu
}

// AddOpen adds f to the "open" field.
func (cu *CandleUpdate) AddOpen(f float64) *CandleUpdate {
	cu.mutation.AddOpen(f)
	return cu
}

// SetHigh sets the "high" field.
func (cu *CandleUpdate) SetHigh(f float64) *CandleUpdate {
	cu.mutation.ResetHigh()
	cu.mutation.SetHigh(f)
	return cu
}

// SetNillableHigh sets the "high" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableHigh(f *float64) *CandleUpdate {
	if f != nil {
		cu.SetHigh(*f)
	}
	return cu
}

// AddHigh adds f to the "high" field.
func (cu *CandleUpdate) AddHigh(f float64) *CandleUpdate {
	cu.mutation.AddHigh(f)
	return cu
}

// SetLow sets the "low" field.
func (cu *CandleUpdate) SetLow(f float64) *CandleUpdate {
	cu.mutation.ResetLow()
	cu.mutation.SetLow(f)
	return cu
}

// SetNillableLow sets the "low" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableLow(f *float64) *CandleUpdate {
	if f != nil {
		cu.SetLow(*f)
	}
	return cu
}

// AddLow adds f to the "low" field.
func (cu *CandleUpdate) AddLow(f float64) *CandleUpdate {
	cu.mutation.AddLow(f)
	return cu
}

// SetClose sets the "close" field.
func (cu *CandleUpdate) SetClose(f float64) *CandleUpdate {
	cu.mutation.ResetClose()
	cu.mutation.SetClose(f)
	return cu
}

// SetNillableClose sets the "close" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableClose(f *float64) *CandleUpdate {
	if f != nil {
		cu.SetClose(*f)
	}
	return cu
}

// AddClose adds f to the "close" field.
func (cu *CandleUpdate) AddClose(f float64) *CandleUpdate {
	cu.mutation.AddClose(f)
	return cu
}

// SetVolume sets the "volume" field.
func (cu *CandleUpdate) SetVolume(f float64) *CandleUpdate {
	cu.mutation.ResetVolume()
	cu.mutation.SetVolume(f)
	return cu
}

// SetNillableVolume sets the "volume" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableVolume(f *float64) *CandleUpdate {
	if f != nil {
		cu.SetVolume(*f)
	}
	return cu
}

// AddVolume adds f to the "volume" field.
func (cu *CandleUpdate) AddVolume(f float64) *CandleUpdate {
	cu.mutation.AddVolume(f)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CandleUpdate) SetCreatedAt(t time.Time) *CandleUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CandleUpdate) SetNillableCreatedAt(t *time.Time) *CandleUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// Mutation returns the CandleMutation object of the builder.
func (cu *CandleUpdate) Mutation() *CandleMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CandleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CandleUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CandleUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CandleUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CandleUpdate) check() error {
	if v, ok := cu.mutation.Timeframe(); ok {
		if err := candle.TimeframeValidator(v); err != nil {
			return &ValidationError{Name: "timeframe", err: fmt.Errorf(`ent: validator failed for field "Candle.timeframe": %w`, err)}
		}
	}
	return nil
}

func (cu *CandleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(candle.Table, candle.Columns, sqlgraph.NewFieldSpec(candle.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Exchange(); ok {
		_spec.SetField(candle.FieldExchange, field.TypeString, value)
	}
	if value, ok := cu.mutation.Symbol(); ok {
		_spec.SetField(candle.FieldSymbol, field.TypeString, value)
	}
	if value, ok := cu.mutation.Timeframe(); ok {
		_spec.SetField(candle.FieldTimeframe, field.TypeEnum, value)
	}
	if value, ok := cu.mutation.Timestamp(); ok {
		_spec.SetField(candle.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedTimestamp(); ok {
		_spec.AddField(candle.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.Open(); ok {
		_spec.SetField(candle.FieldOpen, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedOpen(); ok {
		_spec.AddField(candle.FieldOpen, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.High(); ok {
		_spec.SetField(candle.FieldHigh, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedHigh(); ok {
		_spec.AddField(candle.FieldHigh, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.Low(); ok {
		_spec.SetField(candle.FieldLow, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedLow(); ok {
		_spec.AddField(candle.FieldLow, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.Close(); ok {
		_spec.SetField(candle.FieldClose, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedClose(); ok {
		_spec.AddField(candle.FieldClose, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.Volume(); ok {
		_spec.SetField(candle.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedVolume(); ok {
		_spec.AddField(candle.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(candle.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{candle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CandleUpdateOne is the builder for updating a single Candle entity.
type CandleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CandleMutation
}

// SetExchange sets the "exchange" field.
func (cuo *CandleUpdateOne) SetExchange(s string) *CandleUpdateOne {
	cuo.mutation.SetExchange(s)
	return cuo
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableExchange(s *string) *CandleUpdateOne {
	if s != nil {
		cuo.SetExchange(*s)
	}
	return cuo
}

// SetSymbol sets the "symbol" field.
func (cuo *CandleUpdateOne) SetSymbol(s string) *CandleUpdateOne {
	cuo.mutation.SetSymbol(s)
	return cuo
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableSymbol(s *string) *CandleUpdateOne {
	if s != nil {
		cuo.SetSymbol(*s)
	}
	return cuo
}

// SetTimeframe sets the "timeframe" field.
func (cuo *CandleUpdateOne) SetTimeframe(c candle.Timeframe) *CandleUpdateOne {
	cuo.mutation.SetTimeframe(c)
	return cuo
}

// SetNillableTimeframe sets the "timeframe" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableTimeframe(c *candle.Timeframe) *CandleUpdateOne {
	if c != nil {
		cuo.SetTimeframe(*c)
	}
	return cuo
}

// SetTimestamp sets the "timestamp" field.
func (cuo *CandleUpdateOne) SetTimestamp(i int64) *CandleUpdateOne {
	cuo.mutation.ResetTimestamp()
	cuo.mutation.SetTimestamp(i)
	return cuo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableTimestamp(i *int64) *CandleUpdateOne {
	if i != nil {
		cuo.SetTimestamp(*i)
	}
	return cuo
}

// AddTimestamp adds i to the "timestamp" field.
func (cuo *CandleUpdateOne) AddTimestamp(i int64) *CandleUpdateOne {
	cuo.mutation.AddTimestamp(i)
	return cuo
}

// SetOpen sets the "open" field.
func (cuo *CandleUpdateOne) SetOpen(f float64) *CandleUpdateOne {
	cuo.mutation.ResetOpen()
	cuo.mutation.SetOpen(f)
	return cuo
}

// SetNillableOpen sets the "open" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableOpen(f *float64) *CandleUpdateOne {
	if f != nil {
		cuo.SetOpen(*f)
	}
	return cuo
}

// AddOpen adds f to the "open" field.
func (cuo *CandleUpdateOne) AddOpen(f float64) *CandleUpdateOne {
	cuo.mutation.AddOpen(f)
	return cuo
}

// SetHigh sets the "high" field.
func (cuo *CandleUpdateOne) SetHigh(f float64) *CandleUpdateOne {
	cuo.mutation.ResetHigh()
	cuo.mutation.SetHigh(f)
	return cuo
}

// SetNillableHigh sets the "high" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableHigh(f *float64) *CandleUpdateOne {
	if f != nil {
		cuo.SetHigh(*f)
	}
	return cuo
}

// AddHigh adds f to the "high" field.
func (cuo *CandleUpdateOne) AddHigh(f float64) *CandleUpdateOne {
	cuo.mutation.AddHigh(f)
	return cuo
}

// SetLow sets the "low" field.
func (cuo *CandleUpdateOne) SetLow(f float64) *CandleUpdateOne {
	cuo.mutation.ResetLow()
	cuo.mutation.SetLow(f)
	return cuo
}

// SetNillableLow sets the "low" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableLow(f *float64) *CandleUpdateOne {
	if f != nil {
		cuo.SetLow(*f)
	}
	return cuo
}

// AddLow adds f to the "low" field.
func (cuo *CandleUpdateOne) AddLow(f float64) *CandleUpdateOne {
	cuo.mutation.AddLow(f)
	return cuo
}

// SetClose sets the "close" field.
func (cuo *CandleUpdateOne) SetClose(f float64) *CandleUpdateOne {
	cuo.mutation.ResetClose()
	cuo.mutation.SetClose(f)
	return cuo
}

// SetNillableClose sets the "close" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableClose(f *float64) *CandleUpdateOne {
	if f != nil {
		cuo.SetClose(*f)
	}
	return cuo
}

// AddClose adds f to the "close" field.
func (cuo *CandleUpdateOne) AddClose(f float64) *CandleUpdateOne {
	cuo.mutation.AddClose(f)
	return cuo
}

// SetVolume sets the "volume" field.
func (cuo *CandleUpdateOne) SetVolume(f float64) *CandleUpdateOne {
	cuo.mutation.ResetVolume()
	cuo.mutation.SetVolume(f)
	return cuo
}

// SetNillableVolume sets the "volume" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableVolume(f *float64) *CandleUpdateOne {
	if f != nil {
		cuo.SetVolume(*f)
	}
	return cuo
}

// AddVolume adds f to the "volume" field.
func (cuo *CandleUpdateOne) AddVolume(f float64) *CandleUpdateOne {
	cuo.mutation.AddVolume(f)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CandleUpdateOne) SetCreatedAt(t time.Time) *CandleUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CandleUpdateOne) SetNillableCreatedAt(t *time.Time) *CandleUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// Mutation returns the CandleMutation object of the builder.
func (cuo *CandleUpdateOne) Mutation() *CandleMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CandleUpdate builder.
func (cuo *CandleUpdateOne) Where(ps ...predicate.Candle) *CandleUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CandleUpdateOne) Select(field string, fields ...string) *CandleUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Candle entity.
func (cuo *CandleUpdateOne) Save(ctx context.Context) (*Candle, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CandleUpdateOne) SaveX(ctx context.Context) *Candle {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CandleUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CandleUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CandleUpdateOne) check() error {
	if v, ok := cuo.mutation.Timeframe(); ok {
		if err := candle.TimeframeValidator(v); err != nil {
			return &ValidationError{Name: "timeframe", err: fmt.Errorf(`ent: validator failed for field "Candle.timeframe": %w`, err)}
		}
	}
	return nil
}

func (cuo *CandleUpdateOne) sqlSave(ctx context.Context) (_node *Candle, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(candle.Table, candle.Columns, sqlgraph.NewFieldSpec(candle.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Candle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, candle.FieldID)
		for _, f := range fields {
			if !candle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != candle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Exchange(); ok {
		_spec.SetField(candle.FieldExchange, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Symbol(); ok {
		_spec.SetField(candle.FieldSymbol, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Timeframe(); ok {
		_spec.SetField(candle.FieldTimeframe, field.TypeEnum, value)
	}
	if value, ok := cuo.mutation.Timestamp(); ok {
		_spec.SetField(candle.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedTimestamp(); ok {
		_spec.AddField(candle.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.Open(); ok {
		_spec.SetField(candle.FieldOpen, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedOpen(); ok {
		_spec.AddField(candle.FieldOpen, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.High(); ok {
		_spec.SetField(candle.FieldHigh, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedHigh(); ok {
		_spec.AddField(candle.FieldHigh, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.Low(); ok {
		_spec.SetField(candle.FieldLow, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedLow(); ok {
		_spec.AddField(candle.FieldLow, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.Close(); ok {
		_spec.SetField(candle.FieldClose, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedClose(); ok {
		_spec.AddField(candle.FieldClose, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.Volume(); ok {
		_spec.SetField(candle.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedVolume(); ok {
		_spec.AddField(candle.FieldVolume, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(candle.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Candle{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{candle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
