// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/iiiyu/tradingview-ws-client/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/iiiyu/tradingview-ws-client/ent/activesession"
	"github.com/iiiyu/tradingview-ws-client/ent/candle"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ActiveSession is the client for interacting with the ActiveSession builders.
	ActiveSession *ActiveSessionClient
	// Candle is the client for interacting with the Candle builders.
	Candle *CandleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ActiveSession = NewActiveSessionClient(c.config)
	c.Candle = NewCandleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ActiveSession: NewActiveSessionClient(cfg),
		Candle:        NewCandleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ActiveSession: NewActiveSessionClient(cfg),
		Candle:        NewCandleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ActiveSession.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ActiveSession.Use(hooks...)
	c.Candle.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ActiveSession.Intercept(interceptors...)
	c.Candle.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ActiveSessionMutation:
		return c.ActiveSession.mutate(ctx, m)
	case *CandleMutation:
		return c.Candle.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ActiveSessionClient is a client for the ActiveSession schema.
type ActiveSessionClient struct {
	config
}

// NewActiveSessionClient returns a client for the ActiveSession from the given config.
func NewActiveSessionClient(c config) *ActiveSessionClient {
	return &ActiveSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `activesession.Hooks(f(g(h())))`.
func (c *ActiveSessionClient) Use(hooks ...Hook) {
	c.hooks.ActiveSession = append(c.hooks.ActiveSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `activesession.Intercept(f(g(h())))`.
func (c *ActiveSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ActiveSession = append(c.inters.ActiveSession, interceptors...)
}

// Create returns a builder for creating a ActiveSession entity.
func (c *ActiveSessionClient) Create() *ActiveSessionCreate {
	mutation := newActiveSessionMutation(c.config, OpCreate)
	return &ActiveSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ActiveSession entities.
func (c *ActiveSessionClient) CreateBulk(builders ...*ActiveSessionCreate) *ActiveSessionCreateBulk {
	return &ActiveSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActiveSessionClient) MapCreateBulk(slice any, setFunc func(*ActiveSessionCreate, int)) *ActiveSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActiveSessionCreateBulk{err: fmt.Errorf("calling to ActiveSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActiveSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActiveSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ActiveSession.
func (c *ActiveSessionClient) Update() *ActiveSessionUpdate {
	mutation := newActiveSessionMutation(c.config, OpUpdate)
	return &ActiveSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActiveSessionClient) UpdateOne(as *ActiveSession) *ActiveSessionUpdateOne {
	mutation := newActiveSessionMutation(c.config, OpUpdateOne, withActiveSession(as))
	return &ActiveSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActiveSessionClient) UpdateOneID(id uuid.UUID) *ActiveSessionUpdateOne {
	mutation := newActiveSessionMutation(c.config, OpUpdateOne, withActiveSessionID(id))
	return &ActiveSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ActiveSession.
func (c *ActiveSessionClient) Delete() *ActiveSessionDelete {
	mutation := newActiveSessionMutation(c.config, OpDelete)
	return &ActiveSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActiveSessionClient) DeleteOne(as *ActiveSession) *ActiveSessionDeleteOne {
	return c.DeleteOneID(as.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActiveSessionClient) DeleteOneID(id uuid.UUID) *ActiveSessionDeleteOne {
	builder := c.Delete().Where(activesession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActiveSessionDeleteOne{builder}
}

// Query returns a query builder for ActiveSession.
func (c *ActiveSessionClient) Query() *ActiveSessionQuery {
	return &ActiveSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActiveSession},
		inters: c.Interceptors(),
	}
}

// Get returns a ActiveSession entity by its id.
func (c *ActiveSessionClient) Get(ctx context.Context, id uuid.UUID) (*ActiveSession, error) {
	return c.Query().Where(activesession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActiveSessionClient) GetX(ctx context.Context, id uuid.UUID) *ActiveSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ActiveSessionClient) Hooks() []Hook {
	return c.hooks.ActiveSession
}

// Interceptors returns the client interceptors.
func (c *ActiveSessionClient) Interceptors() []Interceptor {
	return c.inters.ActiveSession
}

func (c *ActiveSessionClient) mutate(ctx context.Context, m *ActiveSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActiveSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActiveSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActiveSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActiveSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ActiveSession mutation op: %q", m.Op())
	}
}

// CandleClient is a client for the Candle schema.
type CandleClient struct {
	config
}

// NewCandleClient returns a client for the Candle from the given config.
func NewCandleClient(c config) *CandleClient {
	return &CandleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `candle.Hooks(f(g(h())))`.
func (c *CandleClient) Use(hooks ...Hook) {
	c.hooks.Candle = append(c.hooks.Candle, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `candle.Intercept(f(g(h())))`.
func (c *CandleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Candle = append(c.inters.Candle, interceptors...)
}

// Create returns a builder for creating a Candle entity.
func (c *CandleClient) Create() *CandleCreate {
	mutation := newCandleMutation(c.config, OpCreate)
	return &CandleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Candle entities.
func (c *CandleClient) CreateBulk(builders ...*CandleCreate) *CandleCreateBulk {
	return &CandleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CandleClient) MapCreateBulk(slice any, setFunc func(*CandleCreate, int)) *CandleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CandleCreateBulk{err: fmt.Errorf("calling to CandleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CandleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CandleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Candle.
func (c *CandleClient) Update() *CandleUpdate {
	mutation := newCandleMutation(c.config, OpUpdate)
	return &CandleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CandleClient) UpdateOne(ca *Candle) *CandleUpdateOne {
	mutation := newCandleMutation(c.config, OpUpdateOne, withCandle(ca))
	return &CandleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CandleClient) UpdateOneID(id uuid.UUID) *CandleUpdateOne {
	mutation := newCandleMutation(c.config, OpUpdateOne, withCandleID(id))
	return &CandleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Candle.
func (c *CandleClient) Delete() *CandleDelete {
	mutation := newCandleMutation(c.config, OpDelete)
	return &CandleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CandleClient) DeleteOne(ca *Candle) *CandleDeleteOne {
	return c.DeleteOneID(ca.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CandleClient) DeleteOneID(id uuid.UUID) *CandleDeleteOne {
	builder := c.Delete().Where(candle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CandleDeleteOne{builder}
}

// Query returns a query builder for Candle.
func (c *CandleClient) Query() *CandleQuery {
	return &CandleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCandle},
		inters: c.Interceptors(),
	}
}

// Get returns a Candle entity by its id.
func (c *CandleClient) Get(ctx context.Context, id uuid.UUID) (*Candle, error) {
	return c.Query().Where(candle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CandleClient) GetX(ctx context.Context, id uuid.UUID) *Candle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CandleClient) Hooks() []Hook {
	return c.hooks.Candle
}

// Interceptors returns the client interceptors.
func (c *CandleClient) Interceptors() []Interceptor {
	return c.inters.Candle
}

func (c *CandleClient) mutate(ctx context.Context, m *CandleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CandleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CandleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CandleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CandleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Candle mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ActiveSession, Candle []ent.Hook
	}
	inters struct {
		ActiveSession, Candle []ent.Interceptor
	}
)
