// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/iiiyu/tradingview-ws-client/ent/activesession"
	"github.com/iiiyu/tradingview-ws-client/ent/candle"
	"github.com/iiiyu/tradingview-ws-client/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeActiveSession = "ActiveSession"
	TypeCandle        = "Candle"
)

// ActiveSessionMutation represents an operation that mutates the ActiveSession nodes in the graph.
type ActiveSessionMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	session_id    *string
	exchange      *string
	symbol        *string
	timeframe     *activesession.Timeframe
	enabled       *bool
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ActiveSession, error)
	predicates    []predicate.ActiveSession
}

var _ ent.Mutation = (*ActiveSessionMutation)(nil)

// activesessionOption allows management of the mutation configuration using functional options.
type activesessionOption func(*ActiveSessionMutation)

// newActiveSessionMutation creates new mutation for the ActiveSession entity.
func newActiveSessionMutation(c config, op Op, opts ...activesessionOption) *ActiveSessionMutation {
	m := &ActiveSessionMutation{
		config:        c,
		op:            op,
		typ:           TypeActiveSession,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withActiveSessionID sets the ID field of the mutation.
func withActiveSessionID(id uuid.UUID) activesessionOption {
	return func(m *ActiveSessionMutation) {
		var (
			err   error
			once  sync.Once
			value *ActiveSession
		)
		m.oldValue = func(ctx context.Context) (*ActiveSession, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ActiveSession.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withActiveSession sets the old ActiveSession of the mutation.
func withActiveSession(node *ActiveSession) activesessionOption {
	return func(m *ActiveSessionMutation) {
		m.oldValue = func(context.Context) (*ActiveSession, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ActiveSessionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ActiveSessionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ActiveSession entities.
func (m *ActiveSessionMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ActiveSessionMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ActiveSessionMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ActiveSession.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSessionID sets the "session_id" field.
func (m *ActiveSessionMutation) SetSessionID(s string) {
	m.session_id = &s
}

// SessionID returns the value of the "session_id" field in the mutation.
func (m *ActiveSessionMutation) SessionID() (r string, exists bool) {
	v := m.session_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSessionID returns the old "session_id" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldSessionID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSessionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSessionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSessionID: %w", err)
	}
	return oldValue.SessionID, nil
}

// ResetSessionID resets all changes to the "session_id" field.
func (m *ActiveSessionMutation) ResetSessionID() {
	m.session_id = nil
}

// SetExchange sets the "exchange" field.
func (m *ActiveSessionMutation) SetExchange(s string) {
	m.exchange = &s
}

// Exchange returns the value of the "exchange" field in the mutation.
func (m *ActiveSessionMutation) Exchange() (r string, exists bool) {
	v := m.exchange
	if v == nil {
		return
	}
	return *v, true
}

// OldExchange returns the old "exchange" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldExchange(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExchange is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExchange requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExchange: %w", err)
	}
	return oldValue.Exchange, nil
}

// ResetExchange resets all changes to the "exchange" field.
func (m *ActiveSessionMutation) ResetExchange() {
	m.exchange = nil
}

// SetSymbol sets the "symbol" field.
func (m *ActiveSessionMutation) SetSymbol(s string) {
	m.symbol = &s
}

// Symbol returns the value of the "symbol" field in the mutation.
func (m *ActiveSessionMutation) Symbol() (r string, exists bool) {
	v := m.symbol
	if v == nil {
		return
	}
	return *v, true
}

// OldSymbol returns the old "symbol" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldSymbol(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSymbol is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSymbol requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSymbol: %w", err)
	}
	return oldValue.Symbol, nil
}

// ResetSymbol resets all changes to the "symbol" field.
func (m *ActiveSessionMutation) ResetSymbol() {
	m.symbol = nil
}

// SetTimeframe sets the "timeframe" field.
func (m *ActiveSessionMutation) SetTimeframe(a activesession.Timeframe) {
	m.timeframe = &a
}

// Timeframe returns the value of the "timeframe" field in the mutation.
func (m *ActiveSessionMutation) Timeframe() (r activesession.Timeframe, exists bool) {
	v := m.timeframe
	if v == nil {
		return
	}
	return *v, true
}

// OldTimeframe returns the old "timeframe" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldTimeframe(ctx context.Context) (v activesession.Timeframe, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimeframe is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimeframe requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimeframe: %w", err)
	}
	return oldValue.Timeframe, nil
}

// ResetTimeframe resets all changes to the "timeframe" field.
func (m *ActiveSessionMutation) ResetTimeframe() {
	m.timeframe = nil
}

// SetEnabled sets the "enabled" field.
func (m *ActiveSessionMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *ActiveSessionMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *ActiveSessionMutation) ResetEnabled() {
	m.enabled = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ActiveSessionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ActiveSessionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ActiveSessionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ActiveSessionMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ActiveSessionMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the ActiveSession entity.
// If the ActiveSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ActiveSessionMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ActiveSessionMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the ActiveSessionMutation builder.
func (m *ActiveSessionMutation) Where(ps ...predicate.ActiveSession) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ActiveSessionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ActiveSessionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ActiveSession, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ActiveSessionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ActiveSessionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ActiveSession).
func (m *ActiveSessionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ActiveSessionMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.session_id != nil {
		fields = append(fields, activesession.FieldSessionID)
	}
	if m.exchange != nil {
		fields = append(fields, activesession.FieldExchange)
	}
	if m.symbol != nil {
		fields = append(fields, activesession.FieldSymbol)
	}
	if m.timeframe != nil {
		fields = append(fields, activesession.FieldTimeframe)
	}
	if m.enabled != nil {
		fields = append(fields, activesession.FieldEnabled)
	}
	if m.created_at != nil {
		fields = append(fields, activesession.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, activesession.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ActiveSessionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case activesession.FieldSessionID:
		return m.SessionID()
	case activesession.FieldExchange:
		return m.Exchange()
	case activesession.FieldSymbol:
		return m.Symbol()
	case activesession.FieldTimeframe:
		return m.Timeframe()
	case activesession.FieldEnabled:
		return m.Enabled()
	case activesession.FieldCreatedAt:
		return m.CreatedAt()
	case activesession.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ActiveSessionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case activesession.FieldSessionID:
		return m.OldSessionID(ctx)
	case activesession.FieldExchange:
		return m.OldExchange(ctx)
	case activesession.FieldSymbol:
		return m.OldSymbol(ctx)
	case activesession.FieldTimeframe:
		return m.OldTimeframe(ctx)
	case activesession.FieldEnabled:
		return m.OldEnabled(ctx)
	case activesession.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case activesession.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown ActiveSession field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ActiveSessionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case activesession.FieldSessionID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSessionID(v)
		return nil
	case activesession.FieldExchange:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExchange(v)
		return nil
	case activesession.FieldSymbol:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSymbol(v)
		return nil
	case activesession.FieldTimeframe:
		v, ok := value.(activesession.Timeframe)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimeframe(v)
		return nil
	case activesession.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case activesession.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case activesession.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown ActiveSession field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ActiveSessionMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ActiveSessionMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ActiveSessionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ActiveSession numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ActiveSessionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ActiveSessionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ActiveSessionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ActiveSession nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ActiveSessionMutation) ResetField(name string) error {
	switch name {
	case activesession.FieldSessionID:
		m.ResetSessionID()
		return nil
	case activesession.FieldExchange:
		m.ResetExchange()
		return nil
	case activesession.FieldSymbol:
		m.ResetSymbol()
		return nil
	case activesession.FieldTimeframe:
		m.ResetTimeframe()
		return nil
	case activesession.FieldEnabled:
		m.ResetEnabled()
		return nil
	case activesession.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case activesession.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown ActiveSession field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ActiveSessionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ActiveSessionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ActiveSessionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ActiveSessionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ActiveSessionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ActiveSessionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ActiveSessionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ActiveSession unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ActiveSessionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ActiveSession edge %s", name)
}

// CandleMutation represents an operation that mutates the Candle nodes in the graph.
type CandleMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	exchange      *string
	symbol        *string
	timeframe     *candle.Timeframe
	timestamp     *int64
	addtimestamp  *int64
	open          *float64
	addopen       *float64
	high          *float64
	addhigh       *float64
	low           *float64
	addlow        *float64
	close         *float64
	addclose      *float64
	volume        *float64
	addvolume     *float64
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Candle, error)
	predicates    []predicate.Candle
}

var _ ent.Mutation = (*CandleMutation)(nil)

// candleOption allows management of the mutation configuration using functional options.
type candleOption func(*CandleMutation)

// newCandleMutation creates new mutation for the Candle entity.
func newCandleMutation(c config, op Op, opts ...candleOption) *CandleMutation {
	m := &CandleMutation{
		config:        c,
		op:            op,
		typ:           TypeCandle,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCandleID sets the ID field of the mutation.
func withCandleID(id uuid.UUID) candleOption {
	return func(m *CandleMutation) {
		var (
			err   error
			once  sync.Once
			value *Candle
		)
		m.oldValue = func(ctx context.Context) (*Candle, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Candle.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCandle sets the old Candle of the mutation.
func withCandle(node *Candle) candleOption {
	return func(m *CandleMutation) {
		m.oldValue = func(context.Context) (*Candle, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CandleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CandleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Candle entities.
func (m *CandleMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CandleMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CandleMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Candle.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetExchange sets the "exchange" field.
func (m *CandleMutation) SetExchange(s string) {
	m.exchange = &s
}

// Exchange returns the value of the "exchange" field in the mutation.
func (m *CandleMutation) Exchange() (r string, exists bool) {
	v := m.exchange
	if v == nil {
		return
	}
	return *v, true
}

// OldExchange returns the old "exchange" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldExchange(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExchange is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExchange requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExchange: %w", err)
	}
	return oldValue.Exchange, nil
}

// ResetExchange resets all changes to the "exchange" field.
func (m *CandleMutation) ResetExchange() {
	m.exchange = nil
}

// SetSymbol sets the "symbol" field.
func (m *CandleMutation) SetSymbol(s string) {
	m.symbol = &s
}

// Symbol returns the value of the "symbol" field in the mutation.
func (m *CandleMutation) Symbol() (r string, exists bool) {
	v := m.symbol
	if v == nil {
		return
	}
	return *v, true
}

// OldSymbol returns the old "symbol" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldSymbol(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSymbol is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSymbol requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSymbol: %w", err)
	}
	return oldValue.Symbol, nil
}

// ResetSymbol resets all changes to the "symbol" field.
func (m *CandleMutation) ResetSymbol() {
	m.symbol = nil
}

// SetTimeframe sets the "timeframe" field.
func (m *CandleMutation) SetTimeframe(c candle.Timeframe) {
	m.timeframe = &c
}

// Timeframe returns the value of the "timeframe" field in the mutation.
func (m *CandleMutation) Timeframe() (r candle.Timeframe, exists bool) {
	v := m.timeframe
	if v == nil {
		return
	}
	return *v, true
}

// OldTimeframe returns the old "timeframe" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldTimeframe(ctx context.Context) (v candle.Timeframe, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimeframe is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimeframe requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimeframe: %w", err)
	}
	return oldValue.Timeframe, nil
}

// ResetTimeframe resets all changes to the "timeframe" field.
func (m *CandleMutation) ResetTimeframe() {
	m.timeframe = nil
}

// SetTimestamp sets the "timestamp" field.
func (m *CandleMutation) SetTimestamp(i int64) {
	m.timestamp = &i
	m.addtimestamp = nil
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *CandleMutation) Timestamp() (r int64, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldTimestamp(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// AddTimestamp adds i to the "timestamp" field.
func (m *CandleMutation) AddTimestamp(i int64) {
	if m.addtimestamp != nil {
		*m.addtimestamp += i
	} else {
		m.addtimestamp = &i
	}
}

// AddedTimestamp returns the value that was added to the "timestamp" field in this mutation.
func (m *CandleMutation) AddedTimestamp() (r int64, exists bool) {
	v := m.addtimestamp
	if v == nil {
		return
	}
	return *v, true
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *CandleMutation) ResetTimestamp() {
	m.timestamp = nil
	m.addtimestamp = nil
}

// SetOpen sets the "open" field.
func (m *CandleMutation) SetOpen(f float64) {
	m.open = &f
	m.addopen = nil
}

// Open returns the value of the "open" field in the mutation.
func (m *CandleMutation) Open() (r float64, exists bool) {
	v := m.open
	if v == nil {
		return
	}
	return *v, true
}

// OldOpen returns the old "open" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldOpen(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpen is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpen requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpen: %w", err)
	}
	return oldValue.Open, nil
}

// AddOpen adds f to the "open" field.
func (m *CandleMutation) AddOpen(f float64) {
	if m.addopen != nil {
		*m.addopen += f
	} else {
		m.addopen = &f
	}
}

// AddedOpen returns the value that was added to the "open" field in this mutation.
func (m *CandleMutation) AddedOpen() (r float64, exists bool) {
	v := m.addopen
	if v == nil {
		return
	}
	return *v, true
}

// ResetOpen resets all changes to the "open" field.
func (m *CandleMutation) ResetOpen() {
	m.open = nil
	m.addopen = nil
}

// SetHigh sets the "high" field.
func (m *CandleMutation) SetHigh(f float64) {
	m.high = &f
	m.addhigh = nil
}

// High returns the value of the "high" field in the mutation.
func (m *CandleMutation) High() (r float64, exists bool) {
	v := m.high
	if v == nil {
		return
	}
	return *v, true
}

// OldHigh returns the old "high" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldHigh(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHigh is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHigh requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHigh: %w", err)
	}
	return oldValue.High, nil
}

// AddHigh adds f to the "high" field.
func (m *CandleMutation) AddHigh(f float64) {
	if m.addhigh != nil {
		*m.addhigh += f
	} else {
		m.addhigh = &f
	}
}

// AddedHigh returns the value that was added to the "high" field in this mutation.
func (m *CandleMutation) AddedHigh() (r float64, exists bool) {
	v := m.addhigh
	if v == nil {
		return
	}
	return *v, true
}

// ResetHigh resets all changes to the "high" field.
func (m *CandleMutation) ResetHigh() {
	m.high = nil
	m.addhigh = nil
}

// SetLow sets the "low" field.
func (m *CandleMutation) SetLow(f float64) {
	m.low = &f
	m.addlow = nil
}

// Low returns the value of the "low" field in the mutation.
func (m *CandleMutation) Low() (r float64, exists bool) {
	v := m.low
	if v == nil {
		return
	}
	return *v, true
}

// OldLow returns the old "low" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldLow(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLow is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLow requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLow: %w", err)
	}
	return oldValue.Low, nil
}

// AddLow adds f to the "low" field.
func (m *CandleMutation) AddLow(f float64) {
	if m.addlow != nil {
		*m.addlow += f
	} else {
		m.addlow = &f
	}
}

// AddedLow returns the value that was added to the "low" field in this mutation.
func (m *CandleMutation) AddedLow() (r float64, exists bool) {
	v := m.addlow
	if v == nil {
		return
	}
	return *v, true
}

// ResetLow resets all changes to the "low" field.
func (m *CandleMutation) ResetLow() {
	m.low = nil
	m.addlow = nil
}

// SetClose sets the "close" field.
func (m *CandleMutation) SetClose(f float64) {
	m.close = &f
	m.addclose = nil
}

// Close returns the value of the "close" field in the mutation.
func (m *CandleMutation) Close() (r float64, exists bool) {
	v := m.close
	if v == nil {
		return
	}
	return *v, true
}

// OldClose returns the old "close" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldClose(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClose is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClose requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClose: %w", err)
	}
	return oldValue.Close, nil
}

// AddClose adds f to the "close" field.
func (m *CandleMutation) AddClose(f float64) {
	if m.addclose != nil {
		*m.addclose += f
	} else {
		m.addclose = &f
	}
}

// AddedClose returns the value that was added to the "close" field in this mutation.
func (m *CandleMutation) AddedClose() (r float64, exists bool) {
	v := m.addclose
	if v == nil {
		return
	}
	return *v, true
}

// ResetClose resets all changes to the "close" field.
func (m *CandleMutation) ResetClose() {
	m.close = nil
	m.addclose = nil
}

// SetVolume sets the "volume" field.
func (m *CandleMutation) SetVolume(f float64) {
	m.volume = &f
	m.addvolume = nil
}

// Volume returns the value of the "volume" field in the mutation.
func (m *CandleMutation) Volume() (r float64, exists bool) {
	v := m.volume
	if v == nil {
		return
	}
	return *v, true
}

// OldVolume returns the old "volume" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldVolume(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVolume is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVolume requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVolume: %w", err)
	}
	return oldValue.Volume, nil
}

// AddVolume adds f to the "volume" field.
func (m *CandleMutation) AddVolume(f float64) {
	if m.addvolume != nil {
		*m.addvolume += f
	} else {
		m.addvolume = &f
	}
}

// AddedVolume returns the value that was added to the "volume" field in this mutation.
func (m *CandleMutation) AddedVolume() (r float64, exists bool) {
	v := m.addvolume
	if v == nil {
		return
	}
	return *v, true
}

// ResetVolume resets all changes to the "volume" field.
func (m *CandleMutation) ResetVolume() {
	m.volume = nil
	m.addvolume = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *CandleMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CandleMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Candle entity.
// If the Candle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CandleMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CandleMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the CandleMutation builder.
func (m *CandleMutation) Where(ps ...predicate.Candle) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CandleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CandleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Candle, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CandleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CandleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Candle).
func (m *CandleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CandleMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.exchange != nil {
		fields = append(fields, candle.FieldExchange)
	}
	if m.symbol != nil {
		fields = append(fields, candle.FieldSymbol)
	}
	if m.timeframe != nil {
		fields = append(fields, candle.FieldTimeframe)
	}
	if m.timestamp != nil {
		fields = append(fields, candle.FieldTimestamp)
	}
	if m.open != nil {
		fields = append(fields, candle.FieldOpen)
	}
	if m.high != nil {
		fields = append(fields, candle.FieldHigh)
	}
	if m.low != nil {
		fields = append(fields, candle.FieldLow)
	}
	if m.close != nil {
		fields = append(fields, candle.FieldClose)
	}
	if m.volume != nil {
		fields = append(fields, candle.FieldVolume)
	}
	if m.created_at != nil {
		fields = append(fields, candle.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CandleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case candle.FieldExchange:
		return m.Exchange()
	case candle.FieldSymbol:
		return m.Symbol()
	case candle.FieldTimeframe:
		return m.Timeframe()
	case candle.FieldTimestamp:
		return m.Timestamp()
	case candle.FieldOpen:
		return m.Open()
	case candle.FieldHigh:
		return m.High()
	case candle.FieldLow:
		return m.Low()
	case candle.FieldClose:
		return m.Close()
	case candle.FieldVolume:
		return m.Volume()
	case candle.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CandleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case candle.FieldExchange:
		return m.OldExchange(ctx)
	case candle.FieldSymbol:
		return m.OldSymbol(ctx)
	case candle.FieldTimeframe:
		return m.OldTimeframe(ctx)
	case candle.FieldTimestamp:
		return m.OldTimestamp(ctx)
	case candle.FieldOpen:
		return m.OldOpen(ctx)
	case candle.FieldHigh:
		return m.OldHigh(ctx)
	case candle.FieldLow:
		return m.OldLow(ctx)
	case candle.FieldClose:
		return m.OldClose(ctx)
	case candle.FieldVolume:
		return m.OldVolume(ctx)
	case candle.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Candle field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CandleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case candle.FieldExchange:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExchange(v)
		return nil
	case candle.FieldSymbol:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSymbol(v)
		return nil
	case candle.FieldTimeframe:
		v, ok := value.(candle.Timeframe)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimeframe(v)
		return nil
	case candle.FieldTimestamp:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	case candle.FieldOpen:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpen(v)
		return nil
	case candle.FieldHigh:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHigh(v)
		return nil
	case candle.FieldLow:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLow(v)
		return nil
	case candle.FieldClose:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClose(v)
		return nil
	case candle.FieldVolume:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVolume(v)
		return nil
	case candle.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Candle field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CandleMutation) AddedFields() []string {
	var fields []string
	if m.addtimestamp != nil {
		fields = append(fields, candle.FieldTimestamp)
	}
	if m.addopen != nil {
		fields = append(fields, candle.FieldOpen)
	}
	if m.addhigh != nil {
		fields = append(fields, candle.FieldHigh)
	}
	if m.addlow != nil {
		fields = append(fields, candle.FieldLow)
	}
	if m.addclose != nil {
		fields = append(fields, candle.FieldClose)
	}
	if m.addvolume != nil {
		fields = append(fields, candle.FieldVolume)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CandleMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case candle.FieldTimestamp:
		return m.AddedTimestamp()
	case candle.FieldOpen:
		return m.AddedOpen()
	case candle.FieldHigh:
		return m.AddedHigh()
	case candle.FieldLow:
		return m.AddedLow()
	case candle.FieldClose:
		return m.AddedClose()
	case candle.FieldVolume:
		return m.AddedVolume()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CandleMutation) AddField(name string, value ent.Value) error {
	switch name {
	case candle.FieldTimestamp:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTimestamp(v)
		return nil
	case candle.FieldOpen:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOpen(v)
		return nil
	case candle.FieldHigh:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHigh(v)
		return nil
	case candle.FieldLow:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLow(v)
		return nil
	case candle.FieldClose:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddClose(v)
		return nil
	case candle.FieldVolume:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddVolume(v)
		return nil
	}
	return fmt.Errorf("unknown Candle numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CandleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CandleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CandleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Candle nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CandleMutation) ResetField(name string) error {
	switch name {
	case candle.FieldExchange:
		m.ResetExchange()
		return nil
	case candle.FieldSymbol:
		m.ResetSymbol()
		return nil
	case candle.FieldTimeframe:
		m.ResetTimeframe()
		return nil
	case candle.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	case candle.FieldOpen:
		m.ResetOpen()
		return nil
	case candle.FieldHigh:
		m.ResetHigh()
		return nil
	case candle.FieldLow:
		m.ResetLow()
		return nil
	case candle.FieldClose:
		m.ResetClose()
		return nil
	case candle.FieldVolume:
		m.ResetVolume()
		return nil
	case candle.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Candle field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CandleMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CandleMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CandleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CandleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CandleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CandleMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CandleMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Candle unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CandleMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Candle edge %s", name)
}
