apiVersion: v1
kind: Service
metadata:
  name: tradingview-data-service
spec:
  selector:
    app: tradingview-data-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: LoadBalancer
