// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActiveSession is the predicate function for activesession builders.
type ActiveSession func(*sql.Selector)

// Candle is the predicate function for candle builders.
type Candle func(*sql.Selector)
